talesBlogging/blogs/views.py
from flask import render_template, url_for, request, redirect, Blueprint
from flask_login import current_user, login_required
from talesBlogging import db
from talesBlogging.models import BlogPost
from talesBlogging.blogs.forms import BlogPostForm

blogPosts = Blueprint("blogPosts", __name__)

@blogPosts.route("/create", methods=["GET", "POST"])
@login_required
def createPost():

    form = BlogPostForm()

    if form.validate_on_submit():

        blogPost = BlogPost(title=form.title.data, text=form.text.data, userId=current_user.id)
        db.session.add(blogPost)
        db.session.commit()

        return redirect(url_for("core.index"))

    return render_template("createPost.html", form=form)

@blogPosts.route("/<int:blogPostId>")
def blogPost(blogPostId):

    blogPost = BlogPost.query.get_or_404(blogPostId)
    return render_template("blogPost.html", title=blogPost.title, date=blogPost.date, post=blogPost)

@blogPosts.route("/<int:blogPostId>/update", methods=["GET", "POST"])
@login_required
def update(blogPostId):

    blogPost = BlogPost.query.get_or_404(blogPostId)

    if blogPost.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blogPost.title = form.title.data
        blogPost.text = form.text.data
        db.session.commit()

        return redirect(url_for("blogPosts.blogPost", blogPostId=blogPost.id))

    elif request.method == "GET":
        form.title.data = blogPost.title
        form.text.data = blogPost.text

    return render_template("createPost.html", title="Updating", form=form)

@blogPosts.route("/<int:blogPostId>/delete", methods=["GET", "POST"])
@login_required
def deletePost(blogPostId):

    blogPost = BlogPost.query.get_or_404(blogPostId)

    if blogPost.author != current_user:
        abort(403)

    db.session.delete(blogPost)
    db.session.commit()

    return redirect(url_for("core.index"))

talesBlogging/core/views.py
from flask import render_template, request, Blueprint
from talesBlogging.models import BlogPost

core = Blueprint("core", __name__) #"core" (in parentheses) is the name of the blueprint

@core.route("/")
def index():

    page = request.args.get("page", 1, type=int)
    blogPosts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template("index.html", blogPosts=blogPosts, firstPost = blogPosts.items[0])

@core.route("/info")
def info():
    return render_template("info.html")

talesBlogging/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from talesBlogging import db
from talesBlogging.models import User, BlogPost
from talesBlogging.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from talesBlogging.users.pictureHandler import addProfilePic

users = Blueprint("users", __name__)

@users.route("/Sign up", methods=["GET", "POST"])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()

        return redirect(url_for("users.login"))

    return render_template("register.html", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.checkPassword(form.password.data):

            login_user(user)

            #For the case where user was earlier trying to visit a page that requires login
            next = request.args.get("next")

            if next == None or not next[0] == "/":
                next = url_for("core.index")

            return redirect(next)

    return render_template("login.html",form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = addProfilePic(form.picture.data, username)
            current_user.profileImage = pic

        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()

        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profileImage = url_for("static", filename="profilePics/" + current_user.profileImage)

    return render_template("account.html", profileImage=profileImage, form=form)

@users.route("/<username>")
def userPosts(username):

    page = request.args.get("page", 1, type=int) #cycle through posts through pages
    user = User.query.filter_by(username=username).first_or_404() #Grab the user or if there is no user then grab the 404
                                                                 #page
    blogPosts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    #author is backref for the relationship between User and BlogPost

    return render_template("userBlogPosts.html", blogPosts=blogPosts, user=user)

talesBlogging/templates/account.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
      <div align="center">
        <h3>{{current_user.username}}</h3>
        <img src="{{url_for("static", filename="profilePics/" + current_user.profileImage)}}" align="center">
      </div>
    </div>
  </div>

  <div class="container">
    <form action="" method="POST" enctype="multipart/form-data">

      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.username.label(class="form-group")}} {{form.username(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.email.label(class="form-group")}} {{form.email(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.picture.label(class="form-group")}} {{form.picture(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.submit(class="btn btn-secondary")}}
      </div>

    </form>
  </div>

{% endblock %}

talesBlogging/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Tales - A home for budding writers</title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Custom styles -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="../static/blog.css" rel="stylesheet">
    <link href="../static/carousel.css" rel="stylesheet">

  </head>

  <body>

    <div class="container">

      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">

          <div class="col-4 pt-1">
            <a class="text-muted" href="{{url_for("core.info")}}">Discover</a>
          </div>

          <div class="text-center">
            <a class="text-muted" href="#">
              <img src="../static/logo.jpeg" width="40" height="40" align="left">
            </a>
            <a class="blog-header-logo text-dark" href="#">Tales</a>
          </div>

          {% if not current_user.is_authenticated %}
            <div class="col-4 d-flex justify-content-end align-items-center">
              <a class="btn btn-sm btn-outline-secondary" href="{{url_for("users.register")}}">Sign up</a>
            </div>
          {% endif %}

          {% if current_user.is_authenticated %}
            <div class="col-4 d-flex justify-content-end align-items-center">
              <a href="#"></a>
            </div>
          {% endif %}

        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{{url_for("core.index")}}">Home</a>
          {% if current_user.is_authenticated %}
            <a class="p-2 text-muted" href="{{url_for("blogPosts.createPost")}}">Express</a>
          {% endif %}
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          <a class="p-2 text-muted" href="#"></a>
          {% if not current_user.is_authenticated %}
            <a class="p-2 text-muted" href="{{url_for("users.login")}}">Log in</a>
          {% endif %}
          {% if current_user.is_authenticated %}
            <a class="p-2 text-muted" href="{{url_for("users.account")}}">Account</a>
            <a class="p-2 text-muted" href="{{url_for("users.logout")}}">Log out</a>
          {% endif %}
        </nav>
      </div>

    </div>
      {% block content %}

      {% endblock %}

  </body>
</html>

talesBlogging/templates/blogPost.html
{% extends "base.html" %}
{% block content %}


<div class="container">

  <br>
  <div align="center">

    <h3>{{post.title}}</h3><br>
    <p>Written by: {{post.author.username}}<br>
       Published on: {{post.date.strftime("%d-%m-%Y")}}</p>
    <p>{{post.text}}</p><br>

    {% if post.author == current_user %}

      <div>
        <a href="{{url_for("blogPosts.update", blogPostId=post.id)}}">Update</a>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#delModal">Delete</button>
      </div>

    {% endif %}
    
  </div>

  <div class="modal" tabindex="-1" role="dialog" id="delModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you wish to delete your post?</p>
          <p>The actions are undoable.</p>
        </div>
        <div class="modal-footer">

          <form action="{{url_for("blogPosts.deletePost", blogPostId=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

talesBlogging/templates/createPost.html
{% extends "base.html" %}
{% block content %}

<br>
<br>
  <div class="container">
    <form class="form-group" method="POST">

      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.title.label(class="form-control-label")}} {{form.title(class="form-control form-control-lg")}}
      </div>

      <br>
      <div class="form-group">
        {{form.text.label(class="form-control-label")}} {{form.text(class="form-control form-control-lg")}}
      </div>

      <div class="form-group">
        {{form.submit(class="btn btn-secondary")}}
      </div>

    </form>
  </div>

{% endblock %}

talesBlogging/templates/index.html
{% extends "base.html" %}

{% block content %}

  <div class="container">

    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1><a class="display-4 font-italic text-white" href="{{url_for("blogPosts.blogPost", blogPostId=firstPost.id)}}">{{firstPost.title}}</a></h1>
        <a class="lead my-3 text-white" href="{{url_for("users.userPosts", username=firstPost.author.username)}}">{{firstPost.author.username}}</a>
        <p class="lead my-0">{{firstPost.date.strftime("%d-%m-%Y")}}</p>
        <p class="lead my-2"><a href="{{url_for("blogPosts.blogPost", blogPostId=firstPost.id)}}" class="text-white font-weight-bold">Continue reading...</a></p>
      </div>
    </div>

    <!--
    {% for post in blogPosts.items[1:] %}

      <div class="card">
        <div class="card-body">
          <h4><a class="card-title" href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">{{post.title}}</a></h4>
          <a href="{{url_for("users.userPosts", username=post.author.username)}}">Author: {{post.author.username}}</a>
          <p>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
          <a class="btn btn-secondary" href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">Continue reading...</a>
        </div>
      </div>

    {% endfor %}
    -->

    <div class="row mb-2">
      {% for post in blogPosts.items[1:] %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-100">
            <div class="card-body d-flex flex-column align-items-start">
              <h4><a class="card-title" href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">{{post.title}}</a></h4>
              <a href="{{url_for("users.userPosts", username=post.author.username)}}">{{post.author.username}}</a>
              <p>{{post.date.strftime("%d-%m-%Y")}}</p>
              <a href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" src="{{url_for("static", filename="profilePics/" + post.author.profileImage)}}" width=100 height=100>
          </div>
        </div>
      {% endfor %}
    </div>

  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for pageNum in blogPosts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blogPosts.page == pageNum %} <!-- if on the current page, disable clicking-->
          <li class="page-item disabled">
            <a class="page-link" href="{{url_for("core.index", page=pageNum)}}"></a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="{{url_for("core.index", page=pageNum)}}"></a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>

{% endblock %}

talesBlogging/templates/info.html
{% extends "base.html" %}

{% block content %}

<div class="container">

  <main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">

      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>

      <div class="carousel-inner">

        <div class="carousel-item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption text-left">
              <h1>Welcome to Tales!</h1>
              <p>Tales was created to give all the budding writers a prolific place to express their
                 hearts out.
              </p>
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Know about the creator!</h1>
              <p>Designed and developed by Mohit Kakkar, a first year postgrad at IIIT Bangalore.</p>
            </div>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

  </div>

</div>

{% endblock %}

talesBlogging/templates/login.html
{% extends "base.html" %}
{% block content %}

<br>
<br>
<div class="container text-center">

  <h3 class="h3 mb-3 font-weight-normal">Please log in</h3>

  <div class="col-md-4 offset-md-4">
    <form method="POST">

      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.email.label(class="form-group")}} {{form.email(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.password.label(class="form-group")}} {{form.password(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.submit(class="btn btn-secondary")}}
      </div>

    </form>
  </div>

</div>

{% endblock %}

talesBlogging/templates/register.html
{% extends "base.html" %}
{% block content %}

<br>
<br>
<div class="container text-center">

  <h3 class="h3 mb-3 font-weight-normal">Please register</h3>

  <div class="col-md-4 offset-md-4">
    <form method="POST">

      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.email.label(class="form-group")}} {{form.email(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.username.label(class="form-group")}} {{form.username(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.password.label(class="form-group")}} {{form.password(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.passConfirm.label(class="form-group")}} {{form.passConfirm(class="form-control")}}
      </div>

      <div class="form-group">
        {{form.submit(class="btn btn-secondary")}}
      </div>

    </form>
  </div>

</div>

{% endblock %}

talesBlogging/templates/userBlogPosts.html
{% extends "base.html" %}
{% block content %}

  <div class="container">

    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
      <div align="center">
        <h3>Posts by {{user.username}}</h3>
        <img src="{{url_for("static", filename="profilePics/" + user.profileImage)}}">
      </div>
    </div>

    <!-- blogPosts is an object and therefore we use .items -->
    <!--
    {% for post in blogPosts.items %}
      <h4><a href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">{{post.title}}</a></h4>
      <a href="{{url_for("users.userPosts", username=post.author.username)}}">{{post.author.username}}</a>
      <p class="text-muted">{{post.date.strftime("%d-%m-%Y")}}</p>
      <p>{{post.text[:100]}}</p>
      <p><a href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">Continue reading</a></p>
    {% endfor %} -->


    <div class="row mb-2">
      {% for post in blogPosts.items %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-100">
            <div class="card-body d-flex flex-column align-items-start">
              <h4><a class="card-title" href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">{{post.title}}</a></h4>
              <a href="{{url_for("users.userPosts", username=post.author.username)}}">{{post.author.username}}</a>
              <p>{{post.date.strftime("%d-%m-%Y")}}</p>
              <a href="{{url_for("blogPosts.blogPost", blogPostId=post.id)}}">Continue reading</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for pageNum in blogPosts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blogPosts.page == pageNum %} <!-- if on the current page, disable clicking-->
          <li class="page-item disabled">
            <a class="page-link" href="{{url_for("users.userPosts", username=user.username, page=pageNum)}}"></a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="{{url_for("users.userPosts", username=user.username, page=pageNum)}}"></a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>

{% endblock %}